Fixing the filesystem
PavelApis/MineSweeper pull request #6
Opened 2022-06-22 13:42 UTC by PavelApis

2022-06-22 15:36 UTC, PavelApis commented
>

2022-06-22 18:27 UTC, mfvanek requested changes

2022-06-22 18:27 UTC, mfvanek commented on .github/workflows/build.yml
> +      - name: Validate with Maven
it doesn't have sense. Your jar is already in local repository

2022-06-22 18:27 UTC, mfvanek commented on pom.xml
> -        <pluginManagement>
Please fix `[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!`

2022-06-23 10:17 UTC, mfvanek approved these changes

2022-06-23 10:26 UTC, merged